#配置端口
server:
  port: 8080

spring:
  #配置gson
  gson:
    #具有Expose注解的属性才会转为json
    exclude-fields-without-expose-annotation: true
    #设置时间转为json的格式
    date-format: yyyy-MM-dd HH:mm:ss
    #格式化json
    pretty-printing: true
    #将null值得属性也转json
    serialize-nulls: true
  http:
    converters:
      #设置使用gson将controller响应的对象转为json字符串
      preferred-json-mapper: gson
  mvc:
    #404时抛出异常
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  #hdfs地址
  hadoop:
    fsUri: hdfs://dev-120.microskynet.com:9000
  #hbase配置zookeeper地址
  hbase:
    config:
      hbase.zookeeper.quorum: dev-120.microskynet.com
      hbase.zookeeper.property.clientPort: 2181
  #kafka配置
  kafka:
    bootstrap-servers: dev-120.microskynet.com:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      batch-size: 16384
      buffer-memory: 33554432
      retries: 0
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: microskynet
      enable-auto-commit: true
      auto-commit-interval: 1000ms
#日志
logging:
  level:
    root: info
    com.lpcheng.microskynet: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss