#配置Tomcat
server:
  port: 80

spring:
  #配置gson
  gson:
    #具有Expose注解的属性才会转为json
    exclude-fields-without-expose-annotation: true
    #设置时间转为json的格式
    date-format: yyyy-MM-dd HH:mm:ss
    #格式化json
    pretty-printing: true
    #将null值得属性也转json
    serialize-nulls: true
  http:
    converters:
      #设置使用gson将controller响应的对象转为json字符串
      preferred-json-mapper: gson
  mvc:
    #404时抛出异常
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

#配置日志
logging:
  level:
    root: info
    com.lpcheng.microskynet: debug
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss

hbase:
  config:
    hbase.zookeeper.quorum: dev-120.wtw.com
    hbase.zookeeper.property.clientPort: 2181
    fs.defaultFS: hdfs://dev-120.wtw.com:8020
    fs.trash.interval: 1